services:
  edgs-app:
    build: . # Instructs Docker Compose to build using the Dockerfile in the current directory
    image: edgs-app # This is the name of the image you built
    ports:
      - "7863:7862" # For Gradio, if you still use it
      - "8889:8888" # Map port 8889 for JupyterLab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Use all available GPUs
              capabilities: [gpu] # Request GPU capabilities
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./data:/EDGS/data # Example: map a local 'data' folder to '/EDGS/data' in the container
      - ./outputs:/EDGS/outputs # Example: map a local 'output' folder
      - ./script:/EDGS/script # Example: map a local 'scripts' folder
      - ./source:/EDGS/source # Example: map a local 'sources' folder
      - ./configs:/EDGS/configs # Example: map a local 'config' folder
      - ./notebooks:/EDGS/notebooks # Map a local 'notebooks' folder for JupyterLab
      - ./submodules:/EDGS/submodules # Map submodules for gaussian-splatting and RoMa
    stdin_open: true # Keep STDIN open for interactive processes
    tty: true        # Allocate a TTY