services:
  edgs-app:
    build: . # Instructs Docker Compose to build using the Dockerfile in the current directory
    image: edgs-app # This is the name of the image you built
    ports:
      - "7862:7862" # For Gradio, if you still use it
      - "8888:8888" # Map port 8888 for JupyterLab
    runtime: nvidia # Use NVIDIA runtime for GPU support
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./data:/EDGS/data # Example: map a local 'data' folder to '/EDGS/data' in the container
      - ./outputs:/EDGS/outputs # Example: map a local 'output' folder
      - ./script:/EDGS/script # Example: map a local 'scripts' folder
      - ./source:/EDGS/source # Example: map a local 'sources' folder
      - ./configs:/EDGS/configs # Example: map a local 'config' folder
      - ./notebooks:/EDGS/notebooks # Map a local 'notebooks' folder for JupyterLab
    stdin_open: true # Keep STDIN open for interactive processes
    tty: true        # Allocate a TTY