defaults:
  - train
  - _self_

# HIGH QUALITY ⭐⭐⭐⭐
# Target: 16GB+ GPUs (RTX 4090, etc.)

train:
  no_densify: False
  gs_epochs: 100000
  reduce_opacity: True
  max_lr: True

gs:
  sh_degree: 3
  opt:
    iterations: 100000
    batch_size: 8

    # Densification
    densify_from_iter: 1000
    densify_until_iter: 35000
    densify_grad_threshold: 0.0003
    percent_dense: 0.005
    densification_interval: 200

    opacity_reset_interval: 2000

    # Learning rates
    position_lr_init: 0.00028
    position_lr_final: 0.0000003
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 90000

    feature_lr: 0.004
    opacity_lr: 0.08
    scaling_lr: 0.0045
    rotation_lr: 0.0018

    lambda_dssim: 0.4
    save_iterations: [20000, 40000, 60000, 80000, 100000]

init_wC:
  use: True
  add_SfM_init: True
  matches_per_ref: 15000
  num_refs: 180
  nns_per_ref: 3
  scaling_factor: 0.001
  proj_err_tolerance: 0.008
