defaults:
  - train
  - _self_

# LOW QUALITY ⭐⭐
# Target: 8-12GB GPUs, SfM-only init (no EDGS/RoMa)

train:
  no_densify: True
  gs_epochs: 45000
  reduce_opacity: True
  max_lr: True

gs:
  sh_degree: 1
  dataset:
    data_device: cpu
  opt:
    iterations: 45000
    batch_size: 1

    opacity_reset_interval: 8000

    # Learning rates
    position_lr_init: 0.00012
    position_lr_final: 0.000003
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 40000

    feature_lr: 0.002
    opacity_lr: 0.03
    scaling_lr: 0.002
    rotation_lr: 0.0008

    lambda_dssim: 0.3
    save_iterations: [7000, 15000, 30000, 45000]

init_wC:
  use: False
  add_SfM_init: True
